### ISSUE TITLE
Create Corporation table

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [RiskBox/QQMS#4]

**Comment by ToniSQL** [comment]
ready to work on Issue No.4 with Lucian!

**Comment by ToniSQL** [comment]
1. Am facut git pull (in momentul de fata sunt urmatoarele fisiere: Issue4, Issue12 si README
2. Am creat Branch-ul pentru Issue4
3. Am creat in local Issue4.sql (codul pentru crearea tabelei Corporation)
4. Am rulat git commit
5. Am rulat git push
6. Nu reusesc sa imi aduc fisierul issue4 din local alaturi de celelalate fisiere (Issue8 si Issue12)

**Comment by ToniSQL** [comment]
![liquibase update issue4](https://user-images.githubusercontent.com/108665283/178071478-05a3f93c-1fcb-41ee-8f9e-015b17a64b81.PNG)

**Comment by ToniSQL** [comment]
Continutul fisierului Issue4.sql

--liquibase formatted sql
/* https://www.liquibase.org/documentation/sql_format.html */

--changeset ToniSQL:12002 labels:create-corporation_table context:issue4

--comment: GO Issue8 after this is being deployed
/* Insert SQL change objects here */
create table Corporation (
    	uid serial primary key not null,
	name varchar(50),
    	timestamp timestamp,
	valid_from date,
	valid_until date
)
--rollback DROP TABLE Corporation;

**Comment by dragos-constantin-stoica** [comment]
Look in the file **liquibqse.properties** and inspect `changeLogFile=issue12-changelog.sql` , it shoul point to your own sql file, like **Issue4.sql**
