### ISSUE TITLE
Create Business Components table

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [RiskBox/QQMS#5]

**Comment by andrdeea** [comment]
hello Dragos,

Please give us a data sample for business component table.

Thanks!

**Comment by dragos-constantin-stoica** [comment]
Hello @andrdeea,

| Version | Component | Service | 
| --- | --- | --- |
| 1 |  Transaction Processing | Product and Service Pricing |

**Comment by dragos-constantin-stoica** [comment]
This is superseeded by issue #62
