### ISSUE TITLE
Create ERCSA table stored procedures

### ISSUE THREAD

**Issue by dragos-constantin-stoica** [RiskBox/QQMS#65]
**Insert following data into ERCSA table:**
For each Corporation we have the same set of ERCSA (Enhanced Risk and Control Self-Assessment). 
Timestamp is the timestamp from server
Valid_from is 01.01.2022
Valid_until is null

| Type | Name | Short Name |
| --- | --- | --- |
| Generic | Control | CONTRL | 
| Generic |  People | PEOPLE | 
| Generic | Execution | EXECTN | 
| Generic | Business Continuity | BUSCON | 
| Generic | Risk Control | RSKCTL | 
| Generic | Internal Logical Access Management | INTLAM | 
| Generic | Physical Access | PHSACC | 
| Generic | Policies and Procedures | POLPRO | 
| Technical |  Data Quality Management | DATQTY | 
| Technical | Vendor Management | VENDOR | 
| Technical | Core Systems Management | CORSYS | 
| Technical | External Logical Access Management | EXTLAM | 
| Technical | Trading | TRDING | 
| Technical | Model Management | MODMGT | 
| Technical | Corporate Credit Assessment and Approval | CCRASS | 
| Technical | Corporate Credit Administration | CCRADM | 
| Technical | Liquidity Management | LIQDTY | 
| Technical | Treasury Deal Management | TRDEAL | 
| Technical | Product Review and Approval | PRDAPP | 
| Technical | Interest Rate Risk Management | INTRAT | 
| Technical | Environment Protection | ENVMNT | 

**Create follwing stored procedures:**
- newCorporationERCSA(scalar: corporation_id) when a new Corporation is created the data above is created for the ERCSA associated with that Corporation
- onInsert (scalar: corporation_id, dataset: type, name, shortname). Check if the type, name and shortname combination already exists for the corporation_id and if does exist update field valid_until with current timestamp and send an error message. If value does not exist then create new entry for the corresponding corporation_id. Call newERCSA procedure for table: Business Component ERCSA.
- onUpdate (scalar: corporation_id, dataset: type, name, shortname) - if the combination corporation_id, type, name, shortname exists then set valid_until field to current timestamp, if does not exist insert new rows.
- onDelete (scalar: corporation_id, dataset: component, service) set valid until - now from server

**Study:** how to partition ERCSA table by corporation_id values.

**Comment by Eugeniu-L** [comment]
Hi @eugen-sp, 

I hope this comment finds you well. I am writing this text to schedule a meeting concerning the issue#65, so could you please confirm your availability and preference related to time and location? 

Best Regards,
Eugeniu.
